<template>
  <div class="legal-page">
    <div class="container">
      <div class="legal-card">
        <h1 class="legal-title">Terms of Service</h1>
        <p class="legal-date">Last updated: February 28, 2026</p>

        <div class="legal-body">
          <p>Welcome to WedChem. By accessing or using our website at wedchem.com (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service.</p>

          <h2>1. About WedChem</h2>
          <p>WedChem is an online marketplace that connects engaged couples with wedding photographers through a proprietary style-matching algorithm. WedChem does not provide photography services. We are a platform that facilitates introductions between couples and independent photographers.</p>

          <h2>2. No Endorsement</h2>
          <p>WedChem does not endorse, recommend, or guarantee any specific photographer listed on the platform. Photographer profiles, portfolios, pricing, and descriptions are provided by the photographers themselves. Match scores generated by our algorithm reflect visual style compatibility only and do not constitute a recommendation, endorsement, or guarantee of quality, reliability, professionalism, or suitability.</p>
          <p>You acknowledge that any hiring decision, contract, or transaction you enter into with a photographer is solely between you and the photographer. WedChem is not a party to any agreement between couples and photographers.</p>

          <h2>3. User Accounts</h2>
          <p>You must provide accurate, complete information when creating an account. You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account. You must be at least 18 years old to create an account.</p>

          <h2>4. Photographer Listings</h2>
          <p>Photographers who register on WedChem agree to:</p>
          <ul>
            <li>Provide truthful, accurate information about their business, experience, and pricing</li>
            <li>Only upload photos they own or have rights to display</li>
            <li>Maintain professional conduct in all communications through the platform</li>
            <li>Not misrepresent their location, availability, or credentials</li>
          </ul>
          <p>WedChem reserves the right to review, approve, reject, or remove any photographer listing at our sole discretion, for any reason, including but not limited to quality standards, accuracy of information, or violations of these Terms.</p>

          <h2>5. Couple Accounts</h2>
          <p>Couples who use WedChem agree to use the platform in good faith, provide accurate information about their wedding plans, and communicate respectfully with photographers.</p>

          <h2>6. Fees & Payments</h2>
          <p>WedChem is free for couples. Photographers may use the platform for free or subscribe to a Featured listing for enhanced visibility. Featured subscriptions are billed monthly or annually as selected at checkout. All payments are processed by Stripe. You may cancel your subscription at any time; cancellation takes effect at the end of the current billing period. Refunds are not provided for partial billing periods.</p>
          <p>WedChem does not charge commissions on bookings or transactions between couples and photographers. WedChem does not process, hold, or facilitate payments between couples and photographers.</p>

          <h2>7. Intellectual Property</h2>
          <p>All content on WedChem, including the algorithm, design, text, graphics, and logos, is owned by WedChem or its licensors. Photographers retain ownership of their uploaded photos and grant WedChem a non-exclusive, royalty-free license to display those photos on the platform for the purpose of operating the Service.</p>

          <h2>8. Prohibited Conduct</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any unlawful purpose</li>
            <li>Upload content that infringes on any third party's intellectual property rights</li>
            <li>Scrape, harvest, or collect data from the Service</li>
            <li>Impersonate any person or entity</li>
            <li>Interfere with or disrupt the Service</li>
            <li>Use the platform to spam, harass, or solicit users</li>
          </ul>

          <h2>9. Limitation of Liability</h2>
          <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WEDCHEM SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.</p>
          <p>WedChem is not responsible for the actions, services, quality, or conduct of any photographer or couple on the platform. We do not verify photographers' credentials, insurance, licenses, or background. You are solely responsible for conducting your own due diligence before hiring any photographer.</p>
          <p>In no event shall WedChem's total liability exceed the amount you paid to WedChem in the 12 months preceding the claim.</p>

          <h2>10. Disclaimer of Warranties</h2>
          <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WEDCHEM DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE.</p>

          <h2>11. Indemnification</h2>
          <p>You agree to indemnify and hold harmless WedChem, its officers, directors, employees, and agents from any claims, damages, losses, or expenses arising out of your use of the Service, your violation of these Terms, or your interaction with any other user of the platform.</p>

          <h2>12. Dispute Resolution</h2>
          <p>Any dispute arising from these Terms or your use of the Service shall be resolved through binding arbitration in accordance with the rules of the American Arbitration Association. The arbitration shall take place in the State of Oregon. You waive any right to participate in a class action lawsuit or class-wide arbitration.</p>

          <h2>13. Termination</h2>
          <p>WedChem may suspend or terminate your account at any time, for any reason, with or without notice. Upon termination, your right to use the Service ceases immediately. Sections 2, 7, 9, 10, 11, and 12 survive termination.</p>

          <h2>14. Modifications</h2>
          <p>WedChem reserves the right to modify these Terms at any time. We will notify registered users of material changes via email. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>

          <h2>15. Governing Law</h2>
          <p>These Terms shall be governed by the laws of the State of Oregon, without regard to conflict of law principles.</p>

          <h2>16. Contact</h2>
          <p>Questions about these Terms? Contact us at <a href="mailto:legal@wedchem.com">legal@wedchem.com</a>.</p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.legal-page { padding:120px 0 80px; background:var(--cream); min-height:100vh; }
.legal-card { max-width:760px; margin:0 auto; background:var(--warm-white); border:1px solid var(--light-gray); border-radius:var(--radius-lg); padding:60px 48px; box-shadow:var(--shadow-md); }
.legal-title { font-family:var(--font-display); font-size:2.2rem; font-weight:400; margin-bottom:8px; }
.legal-date { font-size:0.85rem; color:var(--warm-gray); margin-bottom:40px; }
.legal-body h2 { font-family:var(--font-display); font-size:1.2rem; font-weight:500; margin:32px 0 12px; }
.legal-body p { font-size:0.92rem; color:var(--charcoal); line-height:1.8; margin-bottom:16px; }
.legal-body ul { padding-left:24px; margin-bottom:16px; }
.legal-body li { font-size:0.92rem; color:var(--charcoal); line-height:1.8; margin-bottom:6px; }
.legal-body a { color:var(--terracotta); }
@media(max-width:768px) { .legal-card { padding:40px 24px; } }
</style>
